<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset - LuxDemo Estate</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }
        .email-container {
            background-color: #ffffff;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.05);
            border: 1px solid #e0e0e0;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 1px solid #eee;
        }
        .header h1 {
            color: #0056b3;
            font-size: 28px;
            margin: 0;
        }
        .header .subtitle {
            color: #6c757d;
            font-size: 16px;
            margin-top: 5px;
        }
        .content {
            margin-bottom: 30px;
        }
        .content p {
            margin-bottom: 15px;
            font-size: 15px;
        }
        .reset-button {
            display: inline-block;
            background-color: #007bff;
            color: #ffffff;
            padding: 12px 25px;
            border-radius: 8px;
            text-decoration: none;
            font-weight: bold;
            font-size: 16px;
            margin: 20px 0;
        }
        .reset-button:hover {
            background-color: #0056b3;
            color: #ffffff;
        }
        .security-notice {
            background-color: #f8f9fa;
            border-left: 4px solid #007bff;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 13px;
            color: #888;
        }
        .footer p {
            margin: 5px 0;
        }
        .footer a {
            color: #007bff;
            text-decoration: none;
        }
        .footer .company-name {
            font-weight: bold;
            color: #555;
            font-size: 14px;
        }
        .alternative-link {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
            font-size: 14px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <h1>🔐 Password Reset Request</h1>
            <div class="subtitle">LuxDemo Estate CV Maker</div>
        </div>
        
        <div class="content">
            <p>Hello,</p>
            <p>We received a request to reset your password for your LuxDemo Estate CV Maker account.</p>
            <p>If you requested this password reset, please click the button below to set a new password:</p>
            
            <div style="text-align: center;">
                <a href="{{ $actionUrl }}" class="reset-button">Reset My Password</a>
            </div>
            
            <div class="security-notice">
                <strong>🔒 Security Information:</strong><br>
                • This link will expire in 60 minutes<br>
                • If you didn't request this reset, please ignore this email<br>
                • Your password will remain unchanged until you click the link above
            </div>
            
            <div class="alternative-link">
                <strong>Can't click the button?</strong><br>
                Copy and paste this link into your browser:<br>
                <a href="{{ $actionUrl }}" style="color: #007bff; word-break: break-all;">{{ $actionUrl }}</a>
            </div>
            
            <p>If you have any questions or need assistance, please contact our support team.</p>
            <p>Thank you for using LuxDemo Estate!</p>
        </div>
        
        <div class="footer">
            <p class="company-name">LuxDemo Estate</p>
            <p>Professional CV Services</p>
            <p>Sent by: {{ config('mail.from.address') }}</p>
            <p style="margin-top: 15px; font-size: 12px; color: #adb5bd;">
                <strong>Security Notice:</strong> This email is automatically generated by our secure password reset system.<br>
                <strong>Privacy:</strong> Your data is protected and this email contains no harmful content.<br>
                <strong>Contact:</strong> For support, contact us via <a href="mailto:{{ config('mail.from.address') }}" style="color: #007bff;">{{ config('mail.from.address') }}</a>
            </p>
        </div>
    </div>
</body>
</html>
